### ISSUE TITLE
Issues with custom arbitraries when running tests on NCrunch and TFS.

### ISSUE THREAD

**Issue by aignas** [fscheck/FsCheck#398] opened 2017-09-25 14:03 UTC
Hello, I am having really inconsistent behaviour when running on the following test runners:
- TFS
- NCrunch

However, the Resharper test runner is fine.

What the 2 runners that are failing have in common is that they are running tests in parallel in separate processes and the R# runner is running the tests in a single process, AFAIK.

The exception:
```
Exception during test
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target)
   at Xunit.Sdk.ExecutionTimer.Aggregate(Action action)
   at <StartupCode$FsCheck-Xunit>.$PropertyAttribute.testExec@187(PropertyTestCase this, IMessageBus messageBus, Object[] constructorArguments, CancellationTokenSource cancellationTokenSource, XunitTest test, RunSummary summary, TestOutputHelper outputHelper, Unit unitVar0)
System.Exception: The type UnitsNet.Length is not handled automatically by FsCheck. Consider using another type or writing and registering a generator for it.
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FsCheck.ReflectArbitrary.reflectGenObj@129.Invoke(Type t)
   at FsCheck.Common.f@1[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n, Unit _arg1)
   at FsCheck.Common.memoizeWith[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n)
   at FsCheck.Arb.Derive@1138.get_Generator()
   at FsCheck.Arbitrary`1.FsCheck-IArbitrary-get_GeneratorObj()
   at FsCheck.ReflectArbitrary.gs@64.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at FsCheck.ReflectArbitrary.productGen@63[a](FSharpFunc`2 getGenerator, IEnumerable`1 ts, FSharpFunc`2 create)
   at FsCheck.ReflectArbitrary.reflectObj(FSharpFunc`2 getGenerator, Type t)
   at FsCheck.ReflectArbitrary.reflectGenObj@129.Invoke(Type t)
   at FsCheck.Common.f@1[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n, Unit _arg1)
   at FsCheck.Common.memoizeWith[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n)
   at FsCheck.Arb.Derive@1138.get_Generator()
   at FsCheck.Testable.forAll[a,b](Arbitrary`1 arb, FSharpFunc`2 body)
   at FsCheck.Runner.check[a](Config config, a p)
```

or 

```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
---- System.Exception : The type AwtSG.Domain.NavigationUtilities.Latitude is not handled automatically by FsCheck. Consider using another type or writing and registering a generator for it.
Stack trace
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target)
at <StartupCode$FsCheck-Xunit>.$PropertyAttribute.testExec@187(PropertyTestCase this, IMessageBus messageBus, Object[] constructorArguments, CancellationTokenSource cancellationTokenSource, XunitTest test, RunSummary summary, TestOutputHelper outputHelper, Unit unitVar0)
----- Inner Stack Trace -----
at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
at FsCheck.ReflectArbitrary.reflectGenObj@129.Invoke(Type t)
at FsCheck.Common.f@1[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n, Unit _arg1)
at FsCheck.Common.memoizeWith[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n)
at FsCheck.Arb.Derive@1138.get_Generator()
at FsCheck.Arbitrary`1.FsCheck-IArbitrary-get_GeneratorObj()
at FsCheck.ReflectArbitrary.gs@64.GenerateNext(IEnumerable`1& next)
at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
at FsCheck.ReflectArbitrary.productGen@63[a](FSharpFunc`2 getGenerator, IEnumerable`1 ts, FSharpFunc`2 create)
at FsCheck.ReflectArbitrary.reflectObj(FSharpFunc`2 getGenerator, Type t)
at FsCheck.ReflectArbitrary.reflectGenObj@129.Invoke(Type t)
at FsCheck.Common.f@1[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n, Unit _arg1)
at FsCheck.Common.memoizeWith[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n)
at FsCheck.Arb.Derive@1138.get_Generator()
at FsCheck.Testable.forAll[a,b](Arbitrary`1 arb, FSharpFunc`2 body)
at FsCheck.Runner.check[a](Config config, a p)
```

(The second one is taken from a TFS build of a different project)

A minimum working example, which I can reproduce the error with consistently is below.

The `.cs` file:
```
using FsCheck;
using FsCheck.Xunit;
using UnitsNet;
using Xunit;

namespace FsCheckNcrunchExample
{
    public class UnitTest1
    {
        public class Arbitraries
        {
            public static Arbitrary<Length> Lengths()
                => Arb.Default.Float()
                    .Filter(i => i > 0 && i < 100)
                    .Convert(Length.FromMeters, i => i.Meters);
        }

        static UnitTest1()
        {
            Arb.Register<Arbitraries>();
        }

        [Property]
        public void Test1(Length a, Length b)
        {
            Assert.True(true);
        }

        [Property]
        public void Test2(Length a, Length b)
        {
            Assert.True(true);
        }

        [Property]
        public void Test3(Length a, Length b)
        {
            Assert.True(true);
        }

        [Property]
        public void Test4(Length a, Length b)
        {
            Assert.True(true);
        }
    }
}
```

The project file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170425-07" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
    <PackageReference Include="FsCheck.Xunit" Version="*" />
    <PackageReference Include="UnitsNet" Version="*" />
  </ItemGroup>

</Project>
```

The dependency tree in Visual Studio:
<img width="210" alt="capture" src="https://user-images.githubusercontent.com/240938/30812421-607b0544-a213-11e7-8d2d-06c7db1c2c61.PNG">

**Comment by kurtschelfthout** [comment] 2017-09-25 14:13
Actually, not sure it's an MT bug. (Could still be. Just checking something first.)

You register the Arbitrary instance using a static init method. But some test runners do not actually trigger static initialization because they instantiate the class using reflection.

If you replace `Property` with `Property(Arbitrary=typeof<Arbitraries>)` does it work?

Alternatively if you don't want to repeat that for each method, you can use the `Properties` attribute on the class level to set it for all test methods in that class.

**Comment by aignas** [comment] 2017-09-25 14:18
Actually, if I register the arbitraries in the non static constructor, then it is working more reliably. Actually, on NCrunch for my example project it has not failed.

**Comment by aignas** [comment] 2017-09-25 14:21
I got the impression that one *needs* to register it in the `static` constructor after reading [this paragraph from the docs](https://fscheck.github.io/FsCheck/TestData.html#Default-Generators-and-Shrinkers-based-on-type).

**Comment by kurtschelfthout** [comment] 2017-09-25 14:56
>Actually, if I register the arbitraries in the non static constructor, then it is working more reliably. Actually, on NCrunch for my example project it has not failed.

So all works now?

> I got the impression that one needs to register it in the static constructor after reading this paragraph from the docs.

Sorry, I don't see anything about where to call `Register` in there, did I miss it? Or do you mean we should add something, which would make sense :)

**Comment by aignas** [comment] 2017-09-25 15:12
> So all works now?
Yes, everything works now. I think that the problem I had was that the examples in the https://github.com/fscheck/FsCheck/tree/master/examples/FsCheck.XUnit.CSharpExamples did not explicitly show how to setup custom arbitraries and I feel that such an example would be helpful. I remember finding an example where the arbitraries where registered in a static constructor, which had non-static test methods, which is why I had started with this.

I think it might be benefial to add such example to the aforementioned examples directory. Would you like me to paste the example here or add a PR, if at all?

**Comment by kurtschelfthout** [comment] 2017-09-25 15:13
> I think it might be benefial to add such example to the aforementioned examples directory. Would you like me to paste the example here or add a PR, if at all?

Agreed. PR preferred, but either works.

**Comment by kurtschelfthout** [comment] 2017-09-27 19:48
Going to close this as the issue is resolved, please don't let that stop you from contributing an example or even better documentation!

**Closed by kurtschelfthout** 2017-09-27 19:48 UTC
Labels: question
