### ISSUE TITLE
Support NUnit 3

### ISSUE THREAD

**Issue by jhamm** [fscheck/FsCheck#98] opened 2015-05-14 01:26 UTC
Currrently NUnit v3 is in Beta. I have the updates to support it in the my branch [jhamm/FsCheck](https://github.com/jhamm/FsCheck) in the support-nunit3 branch.

The FsCheck.NUnit.Addins project was not needed to support NUnit 3, so I removed it.

The branch is not ready to be merged into the main branch because it is still in beta and not all of the related projects, like [NUnit.Runners](https://www.nuget.org/packages/NUnit.Runners/), support NUnit 3 yet. For testing, I built and changed the references to pointed the references to the local copies of the dll's.

**Comment by kurtschelfthout** [comment] 2015-05-21 09:07
Cool, would be great to get rid of that stuff. It's been causing a lot of issues.

**Comment by kurtschelfthout** [comment] 2015-08-31 20:15
Alright the PR is now merged and cleaned up all the stuff I expected it to clean up, so as soon as NUnit3 hits the street this is going out the door too.

Meanwhile, please test like crazy via the AppVeryor feed, 2.1.0-b296 and report any issues here.

**Comment by kkm000** [comment] 2015-10-01 22:29
Hi @kurtschelfthout, NUnit 3 is said to be in the latest stages of beta, and production-ready for all practical purposes. Would it be very hard to publish a pre-release package of `FSCheck.NUnit` on NuGet? If you do not want to do that for any reason, then how can I build a package for our internal use--is the tip of the nunit3 branch the correct source?

**Comment by kurtschelfthout** [comment] 2015-10-02 07:48
Yes, that's currently the last one, but I should merge from main and change the version. That version won't have xunit2 support in it. Don't know if you care. I think it should be good enough to test NUnit 3 for now. I'll update this thread when I have an updated version.

**Comment by kkm000** [comment] 2015-10-02 18:54
Thanks, that will do it for me. I noticed that later beta labels did not work, only b296. So far looks good (VS2015).

**Comment by kurtschelfthout** [comment] 2015-10-02 19:59
2.2.0-nunit3-b324 on AppVeyor is the latest version - I merged in the changes we did in 2.1 there.

**Comment by kkm000** [comment] 2015-10-05 18:11
Thanks, switching to it.

Did this ever happened to you: all tests are run, and just before the last timing line is printed, the runner hangs for ~34 seconds (I timed it not once?) The extra 34 seconds added to test time when printed at the end. In Visual Studio Test Explorer window, the green bar at the top stops half-way for this time. Everything is responsive, and eventually completes, but this delay is weird. I *think* (not sure though) that this, once happened, will happen every time until VS is restarted. This is in VS2015. I'm going to run a settings reset and repair VS installation just in case.

I do not know if this an NUnit problem or FsCheck. I would bet on NUnit :)

**Comment by kurtschelfthout** [comment] 2015-10-05 19:57
@kkm000 sorry, I have no idea, I don't use NUnit myself. Perhaps someone else can chime in. It does sound like a problem with NUnit, perhaps a thread not being closed quickly enough. Can you break while it is waiting, to figure out what code is being executed?

**Comment by kkm000** [comment] 2015-10-06 23:00
I'll try to investigate eventually. Too much stuff on hands atm.

**Comment by kkm000** [comment] 2015-10-08 01:13
It's NUnit alone, FsCheck is not the cause: https://github.com/nunit/nunit3-vs-adapter/issues/54

**Comment by kurtschelfthout** [comment] 2015-10-08 08:46
@kkm000 Thanks for looking into!

**Comment by kurtschelfthout** [comment] 2015-11-19 20:42
Looks like NUnit 3.0 is out. Should we switch or wait a bit longer? I think the nunit-3 branch is mostly up to date with main (I've merged back to it now and again).

**Comment by kurtschelfthout** [comment] 2015-11-29 20:12
![1304618376_tumbleweed-gif](https://cloud.githubusercontent.com/assets/164917/11459739/7339652c-96d5-11e5-88aa-95a329842bc6.gif)

**Comment by kurtschelfthout** [comment] 2015-12-25 10:03
I've looked into this. I'll keep the branch of course but not releasing for the time being I can't get NUnit 3 to run static methods, and I can't get NUnit 3 VS test adapter to show any tests (FsCheck or otherwise). By their own admission also most test runners don't run NUnit 3 tests yet.

I'm going to leave this one to "the community" as I'm not personally axed to have NUnit 3 integration, and looks like so far no one else is either.

**Comment by la-yumba** [comment] 2016-01-03 22:12
I'm having trouble with the PropertyAttribute with C# ad nUnit3. 
Setup:

- nUnit3, VS2015 test runner
- locally built the nunit3 branch and referenced dlls

code:

```
using PropertyAttribute = FsCheck.NUnit.PropertyAttribute;
using NUnit.Framework;
using System.Linq;
using FsCheck;

namespace Blah
{
   [TestFixture]
   public class TryFsCheck
   {
      [Property]
      public bool RevRevIsOrig(int[] xs)
         => xs.Reverse().Reverse().SequenceEqual(xs);

      [Test]
      public void RevRevIsOrigTest()
      {
         Prop.ForAll<int[]>(xs => xs.Reverse().Reverse().SequenceEqual(xs))
             .QuickCheckThrowOnFailure();
      }
   }
}
```

output:

```
========== Discover test finished: 31 found (0:00:01.0503616) ==========
------ Run test started ------
NUnit Adapter 3.0.8.0 executing tests is started
Running selected tests in C:\Users\....dll
Loading tests from C:\Users\....dll
Test 0-1037 not found in cache
NUnit Adapter 3.0.8.0 executing tests is finished
========== Run test finished: 1 run (0:00:01.6389192) ==========
```

i.e.: the [Test] with `Prop.ForAll` is run; the [Property] (much cleaner) is not being run... (what does Test 0-1037 not found in cache mean?)

I'm probably doing something wrong... any suggestions?

**Comment by kurtschelfthout** [comment] 2016-01-03 22:23
No idea, sorry.

**Comment by jhamm** [comment] 2016-01-07 04:41
I came across the [https://www.nuget.org/packages/NUnit3TestAdapter](NUnit3TestAdapter) NuGet package. The most recent is CTP8 so it is not fully ready. This could help?

I tried looking into this as well and I was not able to get the VS2015 Test runner working.

The console runner works (I temporarily added the Property from your comment):
powershell> `packages\NUnit.Console\tools\nunit3-console.exe examples\FsCheck.NUnit.CSharpExamples\bin\Debug\FsCheck.NUnit.CSharpExamples.dll`

**Comment by kurtschelfthout** [comment] 2016-01-07 09:41
Yes, that corresponds to my experience - Property does not work with test adapter, but does work with console runner. 

Even just putting a Property in a test dll makes all the tests in that dll disappear. My sense is that this is a problem in the NUnit3 test adapter since the console runner with Property works.

**Comment by xperiandri** [comment] 2016-04-25 22:05
So what is the current status?
Have someone checked if discovery issue was fixed?

**Comment by kurtschelfthout** [comment] 2016-04-26 07:00
The current status is embodied in this issue...so: I have not recently checked whether the discover issue is fixed. Last I know the vs adapter did not discover such properties, for some unknown reason.

I'm definitely open to taking PRs and release FsCheck.NUnit with NUnit 3 (but like with xunit, we'll just move the FsCheck.NUnit package to Nunit 3, don't think it's worth to support both 2 and 3) if the issues with it are fixed. It's unlikely I'll do much work on this myself though, as I don't use NUnit.

**Comment by marklam** [comment] 2017-01-13 12:56
build 2.6.0-nunit3-b698 should work with the NUnit3 VS Adapter, the (in-development) standalone NUnit gui, and NCrunch (tested V2.27.0.3).

**Comment by kurtschelfthout** [comment] 2017-01-13 22:27
@marklam it's a beautiful thing. Thank you very much! 🥇 

I'm planning to release FsCheck.NUnit 2.7.0 to switch to nunit3 support soon. Now for merging to main...

**Closed** 2017-01-14 14:14 UTC
Labels: enhancement, please-test, up-for-grabs
