### ISSUE TITLE
Create ability to run a single test case.

### ISSUE THREAD

**Issue by bradphelan** [fscheck/FsCheck#310] opened 2016-09-23 07:31 UTC
At the moment we can put in a seed to replicate an entire run of unit tests. However as our tests become more complicated they take longer to run. We have large numerical tests running on some big chunks of data. When we disover an edge case we need to debug it. However I can't see a way of only running the single test under failure.

**Comment by ploeh** [comment] 2016-09-24 09:05
When FsCheck finds input that falsifies your property, it reports the values in question in addition to the seed that caused the falsification. It both reports the original and shrunk values, if appropriate:

```fsharp
      Falsifiable, after 13 tests (11 shrinks) (StdGen (2016253613,296208608)):
      Original:
      UriScheme "kt@gY60TwEMr9c"
      Shrunk:
      UriScheme "kt@"
```

Is you property a `let` bound function, or perhaps a class method? If so, you can call it with the data reported by FsCheck, and debug it that way...

**Comment by kurtschelfthout** [comment] 2016-09-24 09:33
@ploeh True, and what I mostly end up doing. Also this gives you a regression unit test that you can (should?) keep around. 

But I still like the suggestion, and it should be relatively straightforward to implement.

**Comment by kurtschelfthout** [comment] 2016-10-15 18:48
Actually it is a bit tricky to implement, with the added constraint to keep backwards compatibility...

**Comment by ploeh** [comment] 2016-10-28 17:11
In the meantime, here's a trick that I just used, because I had a similar problem. Here's the output of a test that I ran:

```fsharp
------ Test started: Assembly: E247.Api.BuckarooPayment.ProtocolTests.dll ------
26 passed, 0 failed, 0 skipped, took 46,03 seconds (xUnit.net 2.1.0 build 3179).

------ Test started: Assembly: E247.Api.BuckarooPayment.UnitTests.dll ------

Test 'E247.Api.BuckarooPayment.BoundaryTests.validateCustomParameter returns correct result on present value' failed: FsCheck.Xunit.PropertyFailedException : 
Falsifiable, after 25 tests (4 shrinks) (StdGen (804078294,296222337)):
Original:
(NonEmptyString "P", ":wI")
[|{Name = "'W>c;r	
	----- Inner Stack Trace -----
	C:\Users\mark\Documents\24-7 Entertainment\Src\e247.api.buckaroopayment\BuckarooPayment.UnitTests\BoundaryTests.fs(72,0): at E247.Api.BuckarooPayment.BoundaryTests.validateCustomParameter returns correct result on present value@67.Invoke(CustomParameter[] customParameters)
	at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a)

47 passed, 1 failed, 0 skipped, took 6,28 seconds (xUnit.net 2.1.0 build 3179).

========== Total Tests: 73 passed, 1 failed, 0 skipped, took 52,94 seconds ==========
```

You'll notice the output is truncated, so I can't see what the actual problem is. (I assume that the truncation happens because there's some sort of non-printable character in the string that wreaks havoc with the output. This seems to happen often with freely generated strings.)

This was an intermittent test failure, so I couldn't rerun the property and hope that text wouldn't be truncated the next time around. This often works, but then the next time the property would pass.

In order to investigate the problem, I activated FsCheck's replay feature (this is the first time I've done this).

The next thing I did, in order to debug, was to set a breakpoint. The problem with this is that in this particular case, the repro runs for 24 successful cases before it hits the erroneous case (the test output states: _Falsifiable, after 25 tests_). It's a bit tedious to hit _continue debugging_ 24 times, so you can configure the breakpoint to only active the 25th time:

![image](https://cloud.githubusercontent.com/assets/242165/19815158/da881692-9d41-11e6-8456-73d662f48c9f.png)

This enabled me to debug (and figure out the problem!) with the tools already available to me.

**Comment by kurtschelfthout** [comment] 2017-03-01 23:03
I plan to add this in v3 because it touches a surprisingly large part of the public API, and I don't see a way of adding the functionality while keeping it compatible. The problem is really that the size of the test case needs to be passed down in addition to the seed to show it in the right place.

**Comment by kurtschelfthout** [comment] 2017-10-13 08:53
Closing this as it's been merged into fscheck3 branch.

**Closed by kurtschelfthout** 2017-10-13 08:53 UTC
Labels: enhancement, v3
