### ISSUE TITLE
support xUnit 2

### ISSUE THREAD

**Issue by ctaggart** [fscheck/FsCheck#86] opened 2015-02-18 02:11 UTC
It would be great if you could add support for xUnit 2 http://xunit.github.io/. May be call the package `FsCheck.Xunit2` if you wish to continue support xUnit 1.

**Comment by kurtschelfthout** [comment] 2015-02-18 09:18
You mean essentially changing xunit dependency version in Fscheck.Xunit package and project, right? Because it already works with the xunit 2.0 runner as far as I can tell.

**Comment by ctaggart** [comment] 2015-02-18 15:50
Correct. Our projects will not build with xunit 2 and FsCheck.Xunit as dependencies.

**Comment by kurtschelfthout** [comment] 2015-02-18 21:14
I'm sympathetic, but given that they are still in prerelease am hesitant to update FsCheck.Xunit. Maybe FsCheck.Xunit2 is a better option. Have my hands full with the C# revamp at the moment though.

**Comment by MartinJohns** [comment] 2015-04-19 17:25
I just wanted to note that Xunit is not in a pre-release state anymore. :-)

**Comment by kurtschelfthout** [comment] 2015-04-20 05:56
Yes…noted ;)

**Comment by jhamm** [comment] 2015-04-23 01:27
I have been working on upgrading XUnit2. There are only a few issues left to work out.

**Comment by jhamm** [comment] 2015-04-24 05:04
Created PR xunit/xunit#403 to fix the handling of attribute parameters that are array types.

**Comment by kurtschelfthout** [comment] 2015-04-24 07:50
:+1:

**Comment by kurtschelfthout** [comment] 2015-04-27 20:17
@jhamm do you think we can put this in the upcoming FsCheck 2.0 release? Any issues on the FsCheck side I can help with?

**Comment by jhamm** [comment] 2015-04-28 03:16
Here is the work I have so far jhamm/FsCheck branch support-xunit2.

If everything is setup, this will run 123 tests, based on https://ci.appveyor.com/project/kurtschelfthout/fscheck, the same number of tests are executed, so that is a good thing.
```
 packages\xunit.runner.console\tools\xunit.console.exe tests\FsCheck.Test\bin\debug\fscheck.test.dll
```

These are the remaining issues that I can see:

- If you get the error "System.Runtime.Serialization.SerializationException : Unable to find assembly 'FsCheck.Xunit, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'."
    - I temporarily fixed this by copying FsCheck.Xunit to the directory "packages\xunit.runner.console\tools"
    - If you get this error when using the VisualStudio Runner, copy FsCheck.Xunit.dll to %TEMP%\VisualStudioTestExplorerExtensions\xunit.runner.visualstudio.2.0.0\build\_common.

- If you get the error: "Exception during discovery: System.ArgumentException: Object of type 'System.Collections.ObjectModel.ReadOnlyCollection`1[System.Reflection.CustomAttributeTypedArgument]' cannot be converted to type 'System.Type[]'. "
    - Build XUnit with the PR from above. As a temporary work around, I manually copied them to the output directory then ran the xunit.console.exe.

**Comment by jhamm** [comment] 2015-04-29 04:51
From what I can see, It looks like the only issues that remain are the PR for XUnit  and the Visual Studio Runner / Nuget.
Should I keep the workaround project until the VS Runner / Nuget one is fixed?

**Comment by kurtschelfthout** [comment] 2015-04-29 07:53
That's very cool, thanks! I think I'll put in a custom build step or something instead of the extra project - it's actually a problem now, which I've halfheartedly worked around by copying the files manually locally. 

Seems like we need to wait for xunit to fix the bug anyway, right? Hopefully this happens in a more reasonable timeframe than the visual studio fix likely will (if ever).

**Comment by kurtschelfthout** [comment] 2015-05-21 09:06
Just following up on status. I put in a workaround for the xunit.runners discovery problem. Does anyone know if that reproduces with VS2015 actually? haven't had the time to try it.

The xunit folks have merged your PR and promised to put it out in their next beta, so if that is there I think I can merge and release this in FsCheck's next 2.0 beta.

**Comment by ploeh** [comment] 2015-05-21 18:44
Recently, I came across this thread and wanted to give my two cents.

For AutoFixture, we had the [same sort of discussion](https://github.com/AutoFixture/AutoFixture/issues/335) a while back regarding compatibility with xUnit.net 2.

The issue is that xUnit.net 2 introduces breaking changes from xUnit.net 1. That's fair enough - they are, after all, making a major new release.

One of the breaking changes is exactly in the `FactAttribute` class that both *AutoFixture.Xunit* and *FsCheck.Xunit* depend on.

This means that *FsCheck.Xunit* currently doesn't work with xUnit.net 2. It also means that if *FsCheck.Xunit* is upgraded to xUnit.net 2, it will no longer be compatible with xUnit.net 1.

This could be unfortunate for people who need to stay on xUnit.net 1 for a while longer. Perhaps they have other Glue Libraries that still depend on xUnit.net 1.

In order to make the switch as painless as possible, we decided to support both main versions for AutoFixture, so there's both *AutoFixture.Xunit* and *AutoFixture.Xunit2*. I'm not sure that I plan to keep *AutoFixture.Xunit* around forever, but for the middle term, I'll keep it around to give users an opportunity to migrate at the time they find appropriate.

My recommendation is to do the same here, even if it means extra work; I'll be happy to help out making the port, if desired.

**Comment by kurtschelfthout** [comment] 2015-05-21 20:37
Yes, all good points. Here's my 2 cents.

My tentative plan was to keep FsCheck 1.0 around (well, it is around already) and keeping that on xUnit 1.9.2. Maybe you can start a v1.0 maintenance branch, backporting your recent PR regarding xunit to the branch starting at https://github.com/fsharp/FsCheck/releases/tag/1.0.4 or maybe a bit later, at https://github.com/fsharp/FsCheck/commit/2b7873a5b1cce291463d08339ee14cec114f0a18 I will be happy to release a 1.0.5 with xunit 1.0 support. 

Then for FsCheck 2.0, since there will be backwards incompatible changes anyway, my hope was to just move to xunit 2 for that release. There is some loss of flexibility there in terms of versions you can use together but hopefully not too bad.

**Comment by ploeh** [comment] 2015-05-21 20:49
OK, that could work as well. Personally, I'm OK with that, as I don't have any problems migrating to xUnit.net 2 anyway, but I don't know if anyone else would have any issues. Let's do a 1.0.5 release if there's demand.

Do you have any timeline on FsCheck 2.0?

I'm currently recording a Pluralsight course, where module 4 will contain some demos with FsCheck, and it would improve the demoed flow somewhat if it I could showcase [the new exception stack trace support](https://github.com/fsharp/FsCheck/pull/99) on xUnit.net 2.0. I don't expect to start recording that part before June 8 (perhaps a bit later).

Is this something I should plan on, or should I make contingency plans?

**Comment by kurtschelfthout** [comment] 2015-05-21 20:55
I'm not sure, because it depends on the xunit folks releasing a new beta with @jhamm 's PR. It's merged and it will go in the next once, but not sure when that will be. Once they do that, I can merge his other PR into FsCheck and release 2.0 beta. I want to do a bit more work on the documentation before the final 2.0 release too.

**Comment by kurtschelfthout** [comment] 2015-05-21 20:57
By the way, here's a crazier idea. 

First, I've gone off the idea of deep integration with runners lately (I use ThrowOnFailure myself all the time now), which obviously is not ideal for anyone. It's not fair to users to make their life harder just to minimize my workload due to my short attention span. 

Second, FsCheck is part of the fsharp organization where it doesn't really belong anymore - see #69 . 

So maybe we could start a new organization, fscheck, split into 3 projects initially: fscheck, fscheck.xunit, fscheck.nunit and I pass on stewardship of fscheck.nunit and xunit to others.  That way these things can evolve separately. And we can have xunit2, and nunit3 #98 (another can of worms I'm not particularly looking forward to) as separate repos and packages. This seems closer to the organization other projects have (for example, xunit) and would split the workload, and give everything more room to grow.

**Comment by ploeh** [comment] 2015-05-21 21:48
I completely support moving FsCheck out of the *fsharp* organisation (and I've left a comment on #69 to that general effect) - whether you want to move it to a new *fscheck* organisation, or your own GitHub account is, in my opinion, not important. It's still 'your' project (unless you want to hand it off to someone else).

Would it help to split the project into three projects, in their own repositories? I don't know. *FsCheck.Xunit* and *FsCheck.NUnit* will always depend on *FsCheck* anyway, so there are limits to how independently they can evolve... Or were you thinking about disconnecting their releases, so that at they can release new versions independently?

... that might be a good idea.

FWIW, in the [AutoFixture](https://github.com/AutoFixture) organisation, we only have a single repository, and even though we have some 10-odd NuGet packages, we always release everything in lock step, which sometimes annoys me a bit - I'm not sure it was the right decision, but it isn't problematic enough that I've felt compelled to do something about it so far.

If you need help with it, I wouldn't mind taking a more active role with *FsCheck.Xunit*.

**Comment by kurtschelfthout** [comment] 2015-05-22 06:45
Moving to my account is a bad idea imo just because it's basically internet suicide to have my last name in a URL ;)

I take your points about the separate repo, probably more trouble than it's worth - binary dependencies and dll hell and duplicating all the infrastructure and figuring out documentation seems pointless.

So I think I'll move to an fscheck organization, but with one repo, like autofixture. I'm very grateful and will take you up on your offer of looking after FsCheck.Xunit.

**Comment by ploeh** [comment] 2015-05-22 07:46
@jhamm, I took a look at your fork, and as far as I can see, the updated version of *FsCheck.Xunit* depends on the *xunit* NuGet package.

For an extensibility project like *FsCheck.Xunit*, this is the incorrect dependency. Instead, *FsCheck.Xunit* [should use *xunit.extensibility.core*](http://xunit.github.io/docs/nuget-packages.html).

When it uses *xunit*, it also drags along references to other libraries, such as *xunit.assert*, which is unwarranted for *FsCheck.Xunit*.

**Comment by jhamm** [comment] 2015-05-22 21:04
Good catch. I will take a look at fixing that.

**Comment by jhamm** [comment] 2015-05-23 02:43
I have updated the reference to use xunit.extensibility.execution. Thanks!

**Comment by kurtschelfthout** [comment] 2015-06-22 07:32
Folks, looks like the xunit team has released the beta with @jhamm's fix we've been craving for. How do you suggest to proceed - can we merge the change and release?

By the way, @ploeh, I looked a bit in your earlier suggestion of keeping both old and new xunit support around at the same time. Given paket only supports one version of each dependency, I think that will cause some significant ceremony. Fyi.

**Comment by ploeh** [comment] 2015-06-22 16:02
Personally, it's not a problem for me - I'd be upgrading to xUnit.net 2 anyway.

My suggestion was only aimed at the hypothetical scenario where someone can't upgrade to xUnit.net 2 because of some other dependency. If such users exist, only offering integration with xUnit.net 2 could leave them in a difficult situation. If such users don't exist, it doesn't matter :smile:

**Comment by SeanU** [comment] 2015-06-22 18:55
I'm currently in that situation, and I wouldn't be offended if the project decides not to maintain compatibility with xUnit 1.9. 

I'm happy to deal with the breaking changes by holding off on upgrading anything while I wait for everyone I depend on to publish an update. If I do eventually find myself waiting longer than I'd like then that will be a good prompting for me to quit being lazy and submit a patch.

-Sean

**Comment by jhamm** [comment] 2015-06-22 21:27
The fix we were looking for was not included in 2.1 beta 2. It was last released on May 4, the PR was merged into xunit master on May 18. I also downloaded the release source zip from https://github.com/xunit/xunit/releases/tag/2.1-beta2 as a second level of verification and it was not there. It looks like we will need to wait for the next release of xunit.

**Comment by kurtschelfthout** [comment] 2015-06-22 22:01
@jhamm you're right - I got confused by the "15 commits to master since this release" thinking that those were the commits that went into it...

@SeanU thanks for not taking offense :+1:

**Comment by jhamm** [comment] 2015-06-24 19:10
The [xunit release notes for May 4 2015](http://xunit.github.io/release-notes/2015-05-03.html) were also confusing: ````BUG: Fixed an issue where arrays of types other than object were causing serialization issues.````

That threw me off for a while too ;)

**Comment by MartinJohns** [comment] 2015-07-01 04:58
Beta 3 got released:
https://www.nuget.org/packages/xunit/2.1.0-beta3-build3029

**Comment by jhamm** [comment] 2015-07-02 15:08
Excellent, I'll take a look on Monday.

**Comment by jhamm** [comment] 2015-07-06 21:26
I have updated the PR. Let me know if I need to change anything.

**Comment by kurtschelfthout** [comment] 2015-07-07 07:17
Cool, thanks! Just the mono bits to wait for now...

**Comment by ErikSchierboom** [comment] 2015-08-06 12:09
I'm a bit late to the discussion, but I'd love to see support for xUnit 2. Great to hear it is being worked on!

**Comment by ErikSchierboom** [comment] 2015-08-19 13:23
I decided to look into the Mono problem and found out that xUnit will add support for a `-noappdomain` argument that allows xUnit to run on Mono. if that is implemented, will that be enough for xUnit 2.0 support to be released?

**Comment by kurtschelfthout** [comment] 2015-08-19 13:52
Yes, I saw that. Yes, if that is released (and it solves the problem, which it should) then we can release xunit 2.0 support.

**Comment by ErikSchierboom** [comment] 2015-08-19 14:00
Brilliant! Can't wait.

**Comment by jhamm** [comment] 2015-08-21 06:43
I am looking into adding the `-noappdomain` option.
I see 2 options of adding support for this:

1) I think it makes sense to do this from the build.fsx file. The issue with this approach is that FAKE does not support this. Looking at adding this would not be difficult, however because this is a new feature for 2.1 Beta4 and higher, I am not sure how to make FAKE only allow this if the xunit2.console is this version or higher. Another option could be to add a string option like:
````
Target "RunTests" (fun _ ->
    !! testAssemblies
    |> Fake.XUnit2Helper.xUnit2 (fun p -> 
            {p with 
                ToolPath = "packages/xunit.runner.console/tools/xunit.console.exe"
                //proposed: this would allow any string
                CustomArg = "-noappdomain"
                ShadowCopy = false }) 
)

````

2) modify the FsCheck.Xunit PropertyAttribute.fs to add one of these (Xunit2 or Xunit2Discoverer). Currently this is not using either.

I would like some input on what you think would be the best approach?

**Comment by kurtschelfthout** [comment] 2015-08-21 07:45
Wow, thanks for the in-depth investigation. The devil is in the details. I would prefer option 1 and document it (after all, it is a mono bug so hopefully in time it should not be needed).

``Xunit2Helper`` seems to be deprecated - and the replacement has the option you need: http://fsharp.github.io/FAKE/apidocs/fake-testing-xunit2.html

**Comment by kurtschelfthout** [comment] 2015-08-27 20:33
For those who would like to test - and please do!

Try build 2.1.0-b283 on appveyor. 

Setup to access AppVeyor feed: https://github.com/fscheck/FsCheck#nuget

**Comment by ploeh** [comment] 2015-08-31 11:56
When I try that, this happens:

```
PM> install-package -Source https://ci.appveyor.com/nuget/fscheck FsCheck.Xunit -Version 2.1.0-b283
Attempting to gather dependencies information for package 'FsCheck.Xunit.2.1.0-b283' with respect to project 'ConwaysGameOfLife04', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'FsCheck.Xunit.2.1.0-b283' with DependencyBehavior 'Lowest'
install-package : Unable to find a version of 'FsCheck' that is compatible with 'FsCheck.Xunit 2.1.0-b283 constraint: FsCheck (≥ 2.1.0)'.
At line:1 char:1
+ install-package -Source https://ci.appveyor.com/nuget/fscheck FsCheck ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

This may be an artefact of attempting to pull from the AppVeyor feed, so I tried I installing the packages 'manually', but still with little success:

```
PM> install-package -Source https://ci.appveyor.com/nuget/fscheck FsCheck -Version 2.1.0-b283
Attempting to gather dependencies information for package 'FsCheck.2.1.0-b283' with respect to project 'ConwaysGameOfLife04', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'FsCheck.2.1.0-b283' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FsCheck.2.1.0-b283'
Resolved actions to install package 'FsCheck.2.1.0-b283'
Adding package 'FsCheck.2.1.0-b283' to folder 'C:\Users\mark\Documents\Katas\ConwaysGameOfLife04\packages'
Added package 'FsCheck.2.1.0-b283' to folder 'C:\Users\mark\Documents\Katas\ConwaysGameOfLife04\packages'
Added package 'FsCheck.2.1.0-b283' to 'packages.config'
Successfully installed 'FsCheck 2.1.0-b283' to ConwaysGameOfLife04

PM> install-package -Source https://ci.appveyor.com/nuget/fscheck FsCheck.Xunit -Version 2.1.0-b283 -IgnoreDependencies
Resolved actions to install package 'FsCheck.Xunit.2.1.0-b283'
Adding package 'FsCheck.Xunit.2.1.0-b283' to folder 'C:\Users\mark\Documents\Katas\ConwaysGameOfLife04\packages'
Added package 'FsCheck.Xunit.2.1.0-b283' to folder 'C:\Users\mark\Documents\Katas\ConwaysGameOfLife04\packages'
Added package 'FsCheck.Xunit.2.1.0-b283' to 'packages.config'
Successfully installed 'FsCheck.Xunit.2.1.0-b283' to ConwaysGameOfLife04

PM> Install-Package xunit.extensibility.core
Attempting to gather dependencies information for package 'xunit.extensibility.core.2.0.0' with respect to project 'ConwaysGameOfLife04', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'xunit.extensibility.core.2.0.0' with DependencyBehavior 'Lowest'
Install-Package : Unable to find a version of 'FSharp.Core' that is compatible with 'FsCheck 2.1.0-b283 constraint: FSharp.Core (≥ 3.1.2.5)'.
At line:1 char:1
+ Install-Package xunit.extensibility.core
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by ploeh** [comment] 2015-08-31 12:07
Changing things around, installing `xunit.core` first, and then installing `FsCheck.Xunit` from the AppVeyor feed using `-IgnoreDependencies`, I managed to reach this configuration:

```
PM> Get-Package

Id                                  Versions               
--                                  --------               
FsCheck                             {2.1.0-b283}           
FsCheck.Xunit                       {2.1.0-b283}           
FSharp.Core                         {3.1.2.5}              
Unquote                             {3.0.0}                
xunit.abstractions                  {2.0.0}                
xunit.core                          {2.1.0-beta4-build3109}
xunit.extensibility.core            {2.1.0-beta4-build3109}
```

This compiles, and I can run *individual* tests using [TestDriven.Net](http://testdriven.net/), but now I can no longer run all tests in my solution or project (which I could before). When I try to run all tests, it simply says *0 Passed, 0 Failed, 0 Skipped*. No error messages.

**Comment by ploeh** [comment] 2015-08-31 12:09
Now I've reverted back to my original configuration, and all is working as it ought to:

```
PM> Get-Package

Id                                  Versions 
--                                  -------- 
FsCheck                             {2.0.7}  
FsCheck.Xunit                       {2.0.7}  
FSharp.Core                         {3.1.2.5}
Unquote                             {3.0.0}  
xunit                               {1.9.2}  
```

**Comment by kurtschelfthout** [comment] 2015-08-31 18:01
@ploeh good catch. Some issues with the dependencies in the nuget packages. Should be fixed in 2.1.0-b293.

**Comment by kurtschelfthout** [comment] 2015-08-31 18:09
@ploeh I don't know about testdriven.net, maybe it got confused with all the packages. In a clean project, when I install 2.1.0-b293 and write a couple of tests, it compiles and I can use the console runner to run them all. Also, when I install xunit.visualstudio.runner, the tests show up in the VS test explorer and I can run them.

That makes me think that from our end everything is fine, more or less. Unfortunately I don't have the bandwidth to investigate weird interactions with every testrunner. But of course, PRs are welcome ;)

**Comment by ploeh** [comment] 2015-09-01 10:46
Version 2.1.0-b293 is much better. I just installed it in a test project, and all NuGet packages were downloaded. The code compiles, and I can run both a single and all tests using TestDriven.Net.

The final package list looks incorrect, though:

```
PM> Get-Package

Id                                  Versions               
--                                  --------               
FsCheck                             {2.1.0-b293}           
FsCheck.Xunit                       {2.1.0-b293}           
FSharp.Core                         {3.1.2.5}              
Unquote                             {3.0.0}                
xunit                               {2.1.0-beta4-build3109}
xunit.abstractions                  {2.0.0}                
xunit.assert                        {2.1.0-beta4-build3109}
xunit.core                          {2.1.0-beta4-build3109}
xunit.extensibility.core            {2.1.0-beta4-build3109}
```

Why are `xunit`, `xunit.core `, and `xunit.assert` there?

As per my [previous comment](#issuecomment-104553947), only `xunit.extensibility.core` should be listed as a dependency. This package will then drag `xunit.abstractions` with it, but that ought to be all.

Nonetheless, if I attempt to force remove some of the seemingly redundant packages, things stop working in various interesting ways - even if the only package I remove is `xunit.assert`, which seems strange.

**Comment by kurtschelfthout** [comment] 2015-09-01 10:59
I don't know what they've done with the 300 different xunit packages, seems slightly insane to me. Is it unreasonable to think that if you're installing FsCheck.Xunit you'd want xunit, as in the whole thing - that is to say, if FsCheck.Xunit is only dependent on xunit.extensibility.core, wouldn't people then have to install xunit separately to get anything done?

**Comment by ploeh** [comment] 2015-09-01 11:05
> Is it unreasonable to think that if you're installing FsCheck.Xunit you'd want xunit

Yes, that's quite unreasonable to think :wink: 

I, for one, want as little to do as possible with `xunit.assert`, because [it's not reasonable](https://xunit.codeplex.com/workitem/9856).

*Still, does it hurt that it's there?* you might ask. *Can't I just avoid using it?*

Even if `xunit.assert` is present, I know well enough to avoid it, but in a team setting (or an open source project), new developers may not know this. It'd make things much easier to manage if it's not there by default.

**Comment by ploeh** [comment] 2015-09-01 11:09
BTW, the issue with Xunit.net `Assert.Equal` [still exists, and confuses other people than me](https://twitter.com/adamchester/status/636101488767471616).

**Comment by kurtschelfthout** [comment] 2015-09-01 11:27
Why is it all so complicated....? :)

Anyway, I have nothing really against FsCheck just depending on what it needs. I'll try changing it later today and see if people complain. Easier to add more dependencies later than to remove them.

I was actually annoyed at the huge dependency tree xunit creates in the FsCheck source. It seems like it pulls in half the world, even when I'm not running on dnx or .netcore. 
https://github.com/fscheck/FsCheck/blob/xunit2/paket.lock

**Comment by ploeh** [comment] 2015-09-01 11:33
OMG :scream: 

It's probably a CoreCLR thing... I must admit that I know next to nothing about that...

**Comment by jhamm** [comment] 2015-09-02 01:40
@ploeh I just ran `paket.exe simplify -i`. Both `xunit.assert` and `xunit.extensibility.execution` are transitive dependencies so they could be removed. They may still remain in the packages folder, but the would be removed from the paket.dependencies. Do you think they should be removed?

**Comment by ploeh** [comment] 2015-09-02 08:43
@jhamm, yes, I think they should be removed from the NuGet package, because not everyone uses Paket.

**Comment by kurtschelfthout** [comment] 2015-09-02 10:04
Am going with @ploeh - though I think the change that is wanted here is in build.fsx: 
https://github.com/fscheck/FsCheck/blob/xunit2/build.fsx#L123

Separately, we can try to simplify the internal dependencies of the FsCheck codebase, which I guess is what @jhamm did with `paket simplify`.

**Comment by kurtschelfthout** [comment] 2015-09-02 20:30
I tried making FsCheck.Xunit depend only on xunit.runner.extensibility, but it needs xunit.assert because it uses XunitException. If I remember correctly this helps with generating the proper error messages for xunit so you can jump to the place of the error from test runners and so on.

**Comment by jhamm** [comment] 2015-09-03 04:33
I took a look at the XunitException class. It does not look like it is adding any thing that we need.

I changed the PropertyFailedException to inherit from Exception and removed the `xunit.assert` package from the project reference and the solution paket.dependencies. There was no changes I could tell from the test failure messages in the FsCheck.XUnit.CSharpExamples projects.

**Comment by jhamm** [comment] 2015-09-03 04:37
I updated to the latest change (8b43a20) in the xunit2 branch and the xunit tests were not being discovered by the VS Test Runner. I reverted back to (f21fb2a) then they worked. It could be something I was doing wrong, but I figured that I would mention it.

**Comment by kurtschelfthout** [comment] 2015-09-03 06:37
@jhamm thanks, I think I forgot to apply the special paket option to make VS test runner extension packages work. I'll take a look later on.

**Comment by kurtschelfthout** [comment] 2015-09-04 20:56
Ok, thanks to @jhamm  and some screwing around on my part we now have 2.1.0-xunit2-b303 on AppVeyor, which no longer pulls in the full xunit.

**Comment by ploeh** [comment] 2015-09-05 12:25
# What's good

Packages look good:

```
PM> Get-Package

Id                                  Versions               
--                                  --------               
FsCheck                             {2.1.0-xunit2-b303}    
FsCheck.Xunit                       {2.1.0-xunit2-b303}    
FSharp.Core                         {3.1.2.5}              
Unquote                             {3.0.0}                
xunit.abstractions                  {2.0.0}                
xunit.extensibility.core            {2.1.0-beta4-build3109}
xunit.extensibility.execution       {2.1.0-beta4-build3109}
```

I can compile a project with this configuration, run my tests with TestDriven.net, and if a property fails, I can easily navigate to the offending line of code using keyboard only. :+1: :smile: :tada: 

# What's bad

[`[<Property(QuietOnSuccess = true)>]`](https://fscheck.github.io/FsCheck/RunningTests.html) no longer works. As far as I can tell, this feature was (inadvertently, I hope) removed in 357664b83ff0399a435ddd84f5a5c2d799e32dbe. :disappointed: 

In my opinion, this should be corrected before release.

**Comment by jhamm** [comment] 2015-09-05 16:50
I have PR #145 that should add this back in from f4a7024c.

**Comment by MartinJohns** [comment] 2015-09-13 17:57
I tried installing the preview FsCheck.Xunit 2.1.0-xunit2-b312 in a F#4 project. This additionally installed "FSharp.Core" version 3.1.2.5. This doesn't seem right to me, as this replaced my original FSharp.Core 4.4.0.0 assembly.

**Comment by kurtschelfthout** [comment] 2015-09-13 20:31
Yes, I don't think it should replace it, also I don't know about the versioning Can you open an issue on https://github.com/fsharp/fsharp ?

**Comment by ctaggart** [comment] 2015-09-15 20:12
@MartinJohns, the NuGet version of 4.0.0.1 contains the Visual Studio 2015 binaries for FSharp.Core assembly version 4.4.0.0. See https://github.com/fsharp/fsharp/issues/444. Here is a good list of assembly versions for each production version of F#. https://github.com/Microsoft/visualfsharp/issues/555#issuecomment-124659645

**Comment by MartinJohns** [comment] 2015-09-18 12:58
Thank you for the clarification @ctaggart! Still I wonder if it's good to reference the FSharp.Core package like this. But I'm not familiar enough with the F# eco-system to evaluate this.

**Comment by ploeh** [comment] 2015-09-18 13:14
@MartinJohns The problem is that FSharp.Core isn't part of the .NET Base Class Library. People who want to use FsCheck with C# may not have F# installed. In those cases, FsCheck simply wouldn't work.

Even if you have F# installed, you may not have the *right* version installed, and again, you run into problems. [Here's an example](http://blog.ploeh.dk/2014/01/30/how-to-use-fsharpcore-430-when-all-you-have-is-431).

Distributing the FSharp.Core package together with the application or library you've created addresses that problem.

**Comment by kurtschelfthout** [comment] 2015-09-19 19:12
@MartinJohns It's tricky. I think adding the NuGet dependency is the least worst option, but as far as I know there isn't one that really works well in all possible cases. I hope that when they distribute the whole framework in 50 packages in CoreCLR there will be a better general solution for these kinds of versioning shenanigans.

**Comment by ErikSchierboom** [comment] 2015-09-22 13:57
I also think adding a dependency on the `FSharp.Core` NuGet package makes sense, as I think people will be using it from C# projects and not all of them will have F# installed.

**Comment by kurtschelfthout** [comment] 2015-09-30 07:00
@ploeh (or anyone else) 2.1.0 was released and @jhamm has kindly updated the xunit branch. I'm going to let you give the final go-ahead. (I will check a bit myself before release too of course, but you're typically more thorough :) ).

The nuget appveyor build version to use is 2.1.0-xunit2-b315.

**Comment by moodmosaic** [comment] 2015-09-30 08:38
@kurtschelfthout, @ploeh, seems to be working fine:

```
install-package -Source
    https://ci.appveyor.com/nuget/fscheck FsCheck.Xunit -Version 2.1.0-xunit2-b315
```

Test Scenarios:

| Passed      | Parametric properties                 |
|:-----------:|:--------------------------------------|
| Ok          | PropertyAttribute                     |
| Ok          | PropertyAttribute-derived types       |
| Ok          | PropertyAttribute with Arbitraries    |
| Ok          | PropertyAttribute with QuietOnSuccess |

| Passed      | Non-parametric properties             |
|:-----------:|:--------------------------------------|
| Ok          | PropertyAttribute                     |
| Ok          | PropertyAttribute-derived types       |
| Ok          | PropertyAttribute with QuietOnSuccess |

**Comment by ploeh** [comment] 2015-09-30 14:13
I've tested this release using the same code base that I've previously used for testing here, and all looks good to me :+1: 

I think this is ready for a release.

**Comment by kurtschelfthout** [comment] 2015-09-30 19:48
We are live with FsCheck 2.1.0 and xunit 2 support.

Don't hate me, and report any issues separately.

Thanks to all who contributed here!

**Closed by kurtschelfthout** 2015-09-30 19:48 UTC
Labels: enhancement, please-test

**Comment by ErikSchierboom** [comment] 2015-10-01 08:41
Brilliant!
