### ISSUE TITLE
FsCheck.Xunit fails to run tests that take a function as argument 

### ISSUE THREAD

**Issue by hansenst** [fscheck/FsCheck#330] opened 2016-12-03 12:04 UTC
Tests that take a function as argument run fine in FsCheck.Nunit, but throw an System.ArgumentException in FsCheck.Xunit.

For example, this sample test
`let testFunc x func = func x`

`[<Property>]`
`let ``Function as parameter sample`` (x:int) (func:int->int) = func x  = testFunc x func`

succeeds when run with Nunit, but Xunit throws this exception:

`System.ArgumentException`
`Object of type 'Microsoft.FSharp.Core.OptimizedClosures+Invoke@3028[System.Int32,System.Int32,FsCheck.Random+StdGen]' cannot be converted to type `'Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,System.Int32]'.`
`   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)`

**Comment by ploeh** [comment] 2016-12-04 09:08
I can't reproduce this behaviour:

```
Output from Repro.Function as parameter sample:
  Ok, passed 100 tests.

1 passed, 0 failed, 0 skipped, took 0,77 seconds (xUnit.net 2.1.0 build 3179).
```

**Comment by hansenst** [comment] 2016-12-04 11:40
Quite possibly this is just me doing something wrong. I did a few more experiments:

**Prerequisite**: I'm using Visual Studio 2015

First scenario:
1. Create a new F#-project (Console Application or Library)
1. Reference FsCheck.Nunit or FsCheck.Xunit
1. Don't upgrade FSharp.Core (my VS defaults to v3.1.25)
1. Add the sample test
1. The test passes 

Second scenario:
1. Create a new F# Console Application project
1. Reference FsCheck.Nunit or FsCheck.Xunit
1. Upgrade FSharp.Core to v4.0.01
1. Add the sample test
1. The test passes 

Third scenario:
1. Create a new F# Library project
1. Reference FsCheck.Nunit or FsCheck.Xunit
1. Upgrade FSharp.Core to v4.0.01
1. Add the sample test
1. The test fails

I got caught out yesterday by running my Xunit from a library-project and the NUnit test from a console-project without paying attention to this difference.

**Comment by ploeh** [comment] 2016-12-04 12:41
Ah, I'd forgotten about the FSharp.Core versioning issue. I've updated FSharp.Core to 4.0.0.1:

```
Id                                  Versions 
--                                  -------- 
FsCheck                             {2.6.2}  
FsCheck.Xunit                       {2.6.2}  
FSharp.Core                         {4.0.0.1}
xunit.abstractions                  {2.0.0}  
xunit.extensibility.core            {2.1.0}  
xunit.extensibility.execution       {2.1.0}  
```

As always, you're going to have to resolve versioning conflicts in `App.config`:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <Paket>True</Paket>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

The property still executes successfully:

```fsharp
Output from Repro.Function as parameter sample:
  Ok, passed 100 tests.

1 passed, 0 failed, 0 skipped, took 0,90 seconds (xUnit.net 2.1.0 build 3179).
```

**Comment by hansenst** [comment] 2016-12-05 10:31
Yep, that turned out to be my problem. I wasn't aware that this issue existed.

Thanks for your help!

**Comment by ploeh** [comment] 2016-12-05 11:04
Did this resolve your problem? Can we close the issue, or do you need help with anything else?

**Comment by hansenst** [comment] 2016-12-05 11:14
Yes, it can be closed now. The issue appeared when the tests were built as class library and adding the runtime information to the dll-config fixed it. The test is passing now when compiled as class library as well as console application.

**Closed** 2016-12-05 16:23 UTC
